#!/usr/bin/env node
/**
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

const fs = require('fs');
const path = require('path');
const { spawn } = require('child_process');

const HVIGOR_HOME = path.join(__dirname, '.hvigor');
const HVIGOR_JAR = path.join(HVIGOR_HOME, 'hvigor.jar');

function main() {
    const args = process.argv.slice(2);
    
    if (!fs.existsSync(HVIGOR_JAR)) {
        console.error('Hvigor environment not initialized. Please run hvigor init first.');
        process.exit(1);
    }
    
    const javaArgs = ['-jar', HVIGOR_JAR].concat(args);
    const javaProcess = spawn('java', javaArgs, { stdio: 'inherit' });
    
    javaProcess.on('close', (code) => {
        process.exit(code);
    });
}

if (require.main === module) {
    main();
}